language:
  - objective-c

env:
  global:
    - MB_PYTHON_VERSION=3.7
    - PKG_NAME=delocate

# Default macOS (xcode image) is 10.13 (xcode 9.4.1) as of 2021-07-09
# See: https://docs.travis-ci.com/user/reference/osx

matrix:
  include:
      - env: MB_PYTHON_VERSION=3.6
      - env: MB_PYTHON_VERSION=3.8
      - env: MB_PYTHON_VERSION=3.9
        env:
          - COVERAGE=1
      # Xcode 12.0 macOS 10.15.5
      - osx_image: xcode12
      # Xcode 9.0 macOS 10.12
      - osx_image: xcode9
      # Xcode 12.3 macOS 11.1
      # We need dual-arch arm64 / x86_64 builds.
      - osx_image: xcode12.3
        env:
          - MB_PYTHON_VERSION=3.9
          - MB_PYTHON_OSX_VER=10.9
          - BUILD_WHEELS=1

before_install:
  - if [ -n "$COVERAGE" ]; then
    pip install coverage;
    pip install codecov;
    fi

install:
  - source multibuild/osx_utils.sh
  - get_macpython_environment $MB_PYTHON_VERSION venv
  - pip install $WHEEL_SPEC -r test-requirements.txt
  - if [ -n "$BUILD_WHEELS" ]; then
        (make clean && make);
    fi
  - pip install .

script:
  - |
    echo $PWD
    mkdir tmp_test_dir
    cd tmp_test_dir
    if [ -n "$COVERAGE" ]; then
      cp ../.coveragerc .
      COVER_ARGS="--cov=$PKG_NAME"
    fi
    pytest $COVER_ARGS --pyargs $PKG_NAME --log-level DEBUG

after_success:
  - |
    if [ -n "$COVERAGE" ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
